# Generated by Django 4.1.2 on 2022-11-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_film_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
