# Generated by Django 4.1.2 on 2022-11-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_film_director_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
    ]
